//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMvw_AppLastLog
    {
        public int IdSolicitud { get; set; }
        public Nullable<System.DateTime> FechaEstatus { get; set; }
        public string Estatus { get; set; }
        public string Usuario { get; set; }
    }
}
