//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMvw_AppFieldStatus
    {
        public string IDEstatus { get; set; }
        public string Estatus { get; set; }
        public string Descripcion { get; set; }
        public string Aplicacion { get; set; }
        public int IDCampo { get; set; }
        public string Nombre { get; set; }
        public string Etiqueta { get; set; }
        public int Longitud { get; set; }
        public string Validaciones { get; set; }
    }
}
