//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMvw_ReportSpecObject
    {
        public int IdSolicitud { get; set; }
        public int IDReport { get; set; }
        public string IDEstatus { get; set; }
        public string ReportName { get; set; }
        public string Parameters { get; set; }
        public string sUsuario { get; set; }
        public string StoreProcedureName { get; set; }
        public string FileName { get; set; }
        public Nullable<int> IDReportType { get; set; }
        public string FileExtensionName { get; set; }
        public byte[] FileObject { get; set; }
    }
}
