//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAutoPrinterLOG
    {
        public int ID { get; set; }
        public int IDSolicitud { get; set; }
        public string stClient { get; set; }
        public int inCreditType { get; set; }
        public int inImageAmount { get; set; }
        public System.DateTime dtLog { get; set; }
        public int inError { get; set; }
        public string stErrorMsg { get; set; }
    }
}
