//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEstatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEstatu()
        {
            this.tblFlujoTrabajos = new HashSet<tblFlujoTrabajo>();
            this.tblLogestatus = new HashSet<tblLogestatu>();
            this.tblSolicitudCampos = new HashSet<tblSolicitudCampos>();
            this.tblCampos = new HashSet<tblCampos>();
            this.tblReports = new HashSet<tblReport>();
        }
    
        public string IDEstatus { get; set; }
        public string Estatus { get; set; }
        public string Descripcion { get; set; }
        public string Aplicacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFlujoTrabajo> tblFlujoTrabajos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLogestatu> tblLogestatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSolicitudCampos> tblSolicitudCampos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCampos> tblCampos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReport> tblReports { get; set; }
    }
}
