//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFlujoTrabajo
    {
        public int IDFlujo { get; set; }
        public int IDActividad { get; set; }
        public int IDTipo { get; set; }
        public string IDEstatus { get; set; }
        public string Aplicacion { get; set; }
    
        public virtual tblEstatu tblEstatu { get; set; }
        public virtual tblFlujo tblFlujo { get; set; }
        public virtual tblFlujoTipos tblFlujoTipos { get; set; }
    }
}
