//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImagene
    {
        public int IdImagenes { get; set; }
        public int IdSolicitud { get; set; }
        public string TipoImagen { get; set; }
        public byte[] Imagen { get; set; }
    }
}
