//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogTarj
    {
        public int IDSolicitud { get; set; }
        public int IDTarj { get; set; }
        public int IDTarjLog { get; set; }
        public System.DateTime dtLog { get; set; }
        public string sUsuario { get; set; }
        public int IDLogCat { get; set; }
    
        public virtual tblLogCat tblLogCat { get; set; }
    }
}
