//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblReport()
        {
            this.tblReportSecurities = new HashSet<tblReportSecurity>();
            this.tblSolicitudReporteObjetoes = new HashSet<tblSolicitudReporteObjeto>();
            this.tblEstatus = new HashSet<tblEstatu>();
        }
    
        public int IDReport { get; set; }
        public string ReportName { get; set; }
        public string Parameters { get; set; }
        public string StoreProcedureName { get; set; }
        public string FileName { get; set; }
        public string FileExtensionName { get; set; }
        public Nullable<int> IDReportType { get; set; }
    
        public virtual tblReportType tblReportType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReportSecurity> tblReportSecurities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSolicitudReporteObjeto> tblSolicitudReporteObjetoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEstatu> tblEstatus { get; set; }
    }
}
