//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSolicitude
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSolicitude()
        {
            this.tblLogestatus = new HashSet<tblLogestatu>();
        }
    
        public int IdSolicitud { get; set; }
        public string NoFolio { get; set; }
        public string RFC { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public System.DateTime Fecha { get; set; }
        public string EstatusActual { get; set; }
        public string TipoCredito { get; set; }
        public string Tienda { get; set; }
        public string Promotor { get; set; }
        public string MotivoEstatus { get; set; }
        public Nullable<System.DateTime> FechaEstatus { get; set; }
        public string Usuario { get; set; }
        public string EstatusRecepcion { get; set; }
        public string PreAprobado { get; set; }
        public Nullable<int> IDpre { get; set; }
        public string completo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLogestatu> tblLogestatus { get; set; }
    }
}
