//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSolicitudesDato
    {
        public int IDSolicitud { get; set; }
        public string Tienda { get; set; }
        public string Promotor { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> TipoCredito { get; set; }
        public Nullable<bool> Sexo { get; set; }
        public Nullable<bool> Nacionalidad { get; set; }
        public string CalleDomicilioActual { get; set; }
        public string NoExterior { get; set; }
        public string NoInterior { get; set; }
        public string Cruzacon { get; set; }
        public string Colonia { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public Nullable<int> CP { get; set; }
        public Nullable<int> TiempoVivirDomicilioAA { get; set; }
        public Nullable<int> TiempoVivirDomicilioMM { get; set; }
        public Nullable<int> TiempoDomicilioAnteriorAA { get; set; }
        public Nullable<int> TiempoDomicilioAnteriorMM { get; set; }
        public string TelefonoCasa { get; set; }
        public string TelefonoOficina { get; set; }
        public string Extension { get; set; }
        public string TelefonoCelular { get; set; }
        public string EMail { get; set; }
        public string Casa { get; set; }
        public Nullable<decimal> PagoMensual { get; set; }
        public Nullable<int> FechaNacimientoDD { get; set; }
        public Nullable<int> FechaNacimientoMM { get; set; }
        public Nullable<int> FechaNacimientoAA { get; set; }
        public string RFC { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> NoDependientes { get; set; }
        public string NombreSolteroConyuge { get; set; }
        public string ConyugeTelefonoCelular { get; set; }
        public string ConyugeEMail { get; set; }
        public Nullable<int> ConyugeFechaNacimientoDD { get; set; }
        public Nullable<int> ConyugeFechaNacimientoMM { get; set; }
        public Nullable<int> ConyugeFechaNacimientoAA { get; set; }
        public string ConyugeRFC { get; set; }
        public string NombreEmpresa { get; set; }
        public string Puesto { get; set; }
        public string Giro { get; set; }
        public string Sector { get; set; }
        public string Caracter { get; set; }
        public Nullable<int> AntiguedadAA { get; set; }
        public Nullable<int> AntiguedadMM { get; set; }
        public Nullable<decimal> IngresosComprobablessueldo { get; set; }
        public Nullable<decimal> IngresosComprobablesConyuge { get; set; }
        public Nullable<decimal> IngresosComprobablesPadres { get; set; }
        public Nullable<decimal> IngresosComprobablesOtros { get; set; }
        public Nullable<decimal> IngresosComprobablesTotal { get; set; }
        public string Escolaridad { get; set; }
        public string EmpleoAnteriorEmpresa { get; set; }
        public Nullable<int> EmpleoAnteriorAntiguedadAA { get; set; }
        public Nullable<int> EmpleoAnteriorAntiguedadMM { get; set; }
        public string EmpleoAnteriorPuesto { get; set; }
        public string Ref1Institucion { get; set; }
        public Nullable<int> Ref1Tipo { get; set; }
        public string Ref1NodeCta { get; set; }
        public string Ref2Institucion { get; set; }
        public Nullable<int> Ref2Tipo { get; set; }
        public string Ref2NodeCta { get; set; }
        public string RefPer1Nombre { get; set; }
        public string RefPer1Telefono { get; set; }
        public string RefPer2Nombre { get; set; }
        public string RefPer2Telefono { get; set; }
        public string RefPer3Nombre { get; set; }
        public string RefPer3Telefono { get; set; }
        public Nullable<int> EdoCuenta { get; set; }
        public string NombreEmpresaConyuge { get; set; }
        public string PuestoConyuge { get; set; }
        public string DomicilioEmpresaConyuge { get; set; }
        public string DomicilioEmpresa { get; set; }
        public string RefPer1Domicilio { get; set; }
        public string RefPer2Domicilio { get; set; }
        public string RefPer3Domicilio { get; set; }
        public string TarjAdic1Nombre { get; set; }
        public string TarjAdic1Telefono { get; set; }
        public string TarjAdic2Nombre { get; set; }
        public string TarjAdic2Telefono { get; set; }
        public string TarjAdic3Nombre { get; set; }
        public string TarjAdic3Telefono { get; set; }
        public Nullable<decimal> MontoCredito { get; set; }
        public Nullable<bool> Tradicional { get; set; }
        public Nullable<bool> PagosFijos { get; set; }
        public string PreAprobado { get; set; }
    }
}
