//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSolicitudReporteObjeto
    {
        public int IDReport { get; set; }
        public int IDSolicitud { get; set; }
        public byte[] FileObject { get; set; }
    
        public virtual tblReport tblReport { get; set; }
    }
}
