//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSolicitudCampos
    {
        public int IDSolicitud { get; set; }
        public string IDEstatus { get; set; }
        public int IDCampo { get; set; }
        public string Value { get; set; }
    
        public virtual tblCampos tblCampos { get; set; }
        public virtual tblEstatu tblEstatu { get; set; }
    }
}
