//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSolUltimoLog
    {
        public int IdSolicitud { get; set; }
        public string Newestatus { get; set; }
        public string Superestatus { get; set; }
        public System.DateTime Fecha { get; set; }
        public string sUsuario { get; set; }
        public byte Terminado { get; set; }
        public Nullable<bool> bNota { get; set; }
        public Nullable<bool> bImagen { get; set; }
    }
}
