//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTarjSolicitude
    {
        public int IDSolicitud { get; set; }
        public int IDTarj { get; set; }
        public byte[] NumTarj { get; set; }
        public string DigitosFin { get; set; }
        public string Segmento { get; set; }
        public string Division { get; set; }
    }
}
