//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuariosClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsuariosClient()
        {
            this.tblReportSecurities = new HashSet<tblReportSecurity>();
            this.tblUsuariosTiendas = new HashSet<tblUsuariosTienda>();
        }
    
        public string sUsuario { get; set; }
        public string sNombre { get; set; }
        public string sAPaterno { get; set; }
        public string sAMaterno { get; set; }
        public string sRelacion { get; set; }
        public string sNombreRelacion { get; set; }
        public string sNombreContacto { get; set; }
        public string sTelContacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReportSecurity> tblReportSecurities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsuariosTienda> tblUsuariosTiendas { get; set; }
    }
}
