//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapcoSolutionTrackings.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuariosTienda
    {
        public string sUsuario { get; set; }
        public string sTienda { get; set; }
        public string Region { get; set; }
        public string Subregion { get; set; }
        public Nullable<bool> Administrador { get; set; }
    
        public virtual tblUsuariosClient tblUsuariosClient { get; set; }
    }
}
